# Easy Lock Scenario - Stationary target for baseline testing
# Expected: At least 1 successful lock

name: easy_lock
difficulty: easy
expected_detection: true
expected_success_locks_min: 1
duration: 30.0

world:
  size: [2000, 2000]
  safe_zone: [200, 200, 1800, 1800]

player:
  position: [600, 500, 100]
  heading: 0
  speed: 5.0

enemies:
  - id: target_1
    behavior: stationary
    position: [700, 500, 100]
    heading: 180
    speed: 0.0

camera:
  width: 640
  height: 480
  fov: 60

lock:
  success_duration: 4.0
  margin_h: 0.5
  margin_v: 0.5
  min_confidence: 0.5

notes: >
  Baseline scenario with a stationary target directly ahead.
  Used to verify the lock-on system works correctly.
